name: Build Docker Image and Upload as Artifact

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t guardian-angel:latest .

    - name: Save Docker image as tar
      run: docker save -o guardian-angel.tar guardian-angel:latest

    - name: Upload Docker image as artifact
      uses: actions/upload-artifact@v4
      with:
        name: guardian-angel
        path: guardian-angel.tar
